# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from recursos import iconosApp_rc


class Ui_FrmLogin(object):
    def setupUi(self, FrmLogin):
        FrmLogin.setObjectName("FrmLogin")
        FrmLogin.resize(380, 345)
        FrmLogin.setMaximumSize(QtCore.QSize(380, 345))
        icon = QtGui.QIcon.fromTheme("HR")
        FrmLogin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(FrmLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.le_usuario = QtWidgets.QLineEdit(self.centralwidget)
        self.le_usuario.setGeometry(QtCore.QRect(30, 170, 321, 25))
        self.le_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.le_usuario.setObjectName("le_usuario")
        self.le_contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.le_contrasena.setGeometry(QtCore.QRect(30, 220, 321, 25))
        self.le_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_contrasena.setAlignment(QtCore.Qt.AlignCenter)
        self.le_contrasena.setObjectName("le_contrasena")
        self.btn_entrar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_entrar.setGeometry(QtCore.QRect(30, 270, 321, 25))
        self.btn_entrar.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.btn_entrar.setObjectName("btn_entrar")
        self.lbl_logo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_logo.setGeometry(QtCore.QRect(130, 20, 131, 131))
        self.lbl_logo.setText("")
        self.lbl_logo.setPixmap(QtGui.QPixmap(":/logoLogin/HrLogo128.png"))
        self.lbl_logo.setObjectName("lbl_logo")
        FrmLogin.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmLogin)
        QtCore.QMetaObject.connectSlotsByName(FrmLogin)

    def retranslateUi(self, FrmLogin):
        _translate = QtCore.QCoreApplication.translate
        FrmLogin.setWindowTitle(_translate("FrmLogin", "Inicio de sesión"))
        self.le_usuario.setPlaceholderText(_translate("FrmLogin", "Nombre de usuario"))
        self.le_contrasena.setPlaceholderText(_translate("FrmLogin", "Contraseña"))
        self.btn_entrar.setText(_translate("FrmLogin", "Entrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmLogin = QtWidgets.QMainWindow()
    ui = Ui_FrmLogin()
    ui.setupUi(FrmLogin)
    FrmLogin.show()
    sys.exit(app.exec_())
