# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmPais.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmPais(object):
    def setupUi(self, FrmPais):
        FrmPais.setObjectName("FrmPais")
        FrmPais.resize(677, 676)
        self.gb_datosPais = QtWidgets.QGroupBox(FrmPais)
        self.gb_datosPais.setGeometry(QtCore.QRect(20, 80, 631, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gb_datosPais.setFont(font)
        self.gb_datosPais.setObjectName("gb_datosPais")
        self.lbl_identificador = QtWidgets.QLabel(self.gb_datosPais)
        self.lbl_identificador.setGeometry(QtCore.QRect(30, 50, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_identificador.setFont(font)
        self.lbl_identificador.setObjectName("lbl_identificador")
        self.lbl_nombre = QtWidgets.QLabel(self.gb_datosPais)
        self.lbl_nombre.setGeometry(QtCore.QRect(30, 130, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_nombre.setFont(font)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_region = QtWidgets.QLabel(self.gb_datosPais)
        self.lbl_region.setGeometry(QtCore.QRect(30, 210, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_region.setFont(font)
        self.lbl_region.setObjectName("lbl_region")
        self.le_identificador = QtWidgets.QLineEdit(self.gb_datosPais)
        self.le_identificador.setGeometry(QtCore.QRect(30, 80, 291, 25))
        self.le_identificador.setReadOnly(True)
        self.le_identificador.setObjectName("le_identificador")
        self.le_nombre = QtWidgets.QLineEdit(self.gb_datosPais)
        self.le_nombre.setGeometry(QtCore.QRect(30, 160, 361, 25))
        self.le_nombre.setObjectName("le_nombre")
        self.cmb_region = QtWidgets.QComboBox(self.gb_datosPais)
        self.cmb_region.setGeometry(QtCore.QRect(30, 250, 291, 25))
        self.cmb_region.setObjectName("cmb_region")
        self.cmb_region.addItem("")
        self.btn_limpiar = QtWidgets.QPushButton(self.gb_datosPais)
        self.btn_limpiar.setGeometry(QtCore.QRect(490, 50, 91, 31))
        self.btn_limpiar.setStyleSheet("color: Black;\n"
"background-color:rgb(255, 255, 255)")
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.btn_agregar = QtWidgets.QPushButton(self.gb_datosPais)
        self.btn_agregar.setGeometry(QtCore.QRect(490, 110, 91, 31))
        self.btn_agregar.setStyleSheet("color: White;\n"
"background-color:rgb(62, 206, 43)")
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_editar = QtWidgets.QPushButton(self.gb_datosPais)
        self.btn_editar.setGeometry(QtCore.QRect(490, 170, 91, 31))
        self.btn_editar.setStyleSheet("color: White;\n"
"background-color: rgb(28, 113, 216)")
        self.btn_editar.setObjectName("btn_editar")
        self.btn_eliminar = QtWidgets.QPushButton(self.gb_datosPais)
        self.btn_eliminar.setGeometry(QtCore.QRect(490, 230, 91, 31))
        self.btn_eliminar.setStyleSheet("color: White;\n"
"background-color: rgb(192, 28, 40)")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.le_buscar = QtWidgets.QLineEdit(FrmPais)
        self.le_buscar.setGeometry(QtCore.QRect(20, 420, 431, 31))
        self.le_buscar.setObjectName("le_buscar")
        self.btn_buscar = QtWidgets.QPushButton(FrmPais)
        self.btn_buscar.setGeometry(QtCore.QRect(510, 420, 91, 31))
        self.btn_buscar.setStyleSheet("color: Black;\n"
"background-color: rgb(255, 255, 255)")
        self.btn_buscar.setObjectName("btn_buscar")
        self.tbv_registroPais = QtWidgets.QTableView(FrmPais)
        self.tbv_registroPais.setGeometry(QtCore.QRect(20, 470, 631, 171))
        self.tbv_registroPais.setObjectName("tbv_registroPais")

        self.retranslateUi(FrmPais)
        QtCore.QMetaObject.connectSlotsByName(FrmPais)

    def retranslateUi(self, FrmPais):
        _translate = QtCore.QCoreApplication.translate
        FrmPais.setWindowTitle(_translate("FrmPais", "Gestión de pais"))
        self.gb_datosPais.setTitle(_translate("FrmPais", "Datos del pais  "))
        self.lbl_identificador.setText(_translate("FrmPais", "Identificador:"))
        self.lbl_nombre.setText(_translate("FrmPais", "Nombre:"))
        self.lbl_region.setText(_translate("FrmPais", "Región:"))
        self.cmb_region.setToolTip(_translate("FrmPais", "<html><head/><body><p>Select</p><p><br/></p></body></html>"))
        self.cmb_region.setItemText(0, _translate("FrmPais", "-- Select --"))
        self.btn_limpiar.setText(_translate("FrmPais", "Limpiar"))
        self.btn_agregar.setText(_translate("FrmPais", "Agregar"))
        self.btn_editar.setText(_translate("FrmPais", "Editar"))
        self.btn_eliminar.setText(_translate("FrmPais", "Eliminar"))
        self.btn_buscar.setText(_translate("FrmPais", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmPais = QtWidgets.QWidget()
    ui = Ui_FrmPais()
    ui.setupUi(FrmPais)
    FrmPais.show()
    sys.exit(app.exec_())
