# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FrmRegion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmRegion(object):
    def setupUi(self, FrmRegion):
        FrmRegion.setObjectName("FrmRegion")
        FrmRegion.resize(811, 600)
        self.centralwidget = QtWidgets.QWidget(FrmRegion)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 80, 751, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lbl_identificador = QtWidgets.QLabel(self.groupBox)
        self.lbl_identificador.setGeometry(QtCore.QRect(20, 40, 101, 17))
        self.lbl_identificador.setObjectName("lbl_identificador")
        self.lbl_nombre = QtWidgets.QLabel(self.groupBox)
        self.lbl_nombre.setGeometry(QtCore.QRect(20, 120, 101, 17))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.le_identificador = QtWidgets.QLineEdit(self.groupBox)
        self.le_identificador.setGeometry(QtCore.QRect(20, 70, 151, 25))
        self.le_identificador.setReadOnly(True)
        self.le_identificador.setObjectName("le_identificador")
        self.le_nombre = QtWidgets.QLineEdit(self.groupBox)
        self.le_nombre.setGeometry(QtCore.QRect(20, 150, 291, 25))
        self.le_nombre.setObjectName("le_nombre")
        self.btn_limpiar = QtWidgets.QPushButton(self.groupBox)
        self.btn_limpiar.setGeometry(QtCore.QRect(600, 40, 89, 25))
        self.btn_limpiar.setObjectName("btn_limpiar")
        self.btn_agregar = QtWidgets.QPushButton(self.groupBox)
        self.btn_agregar.setGeometry(QtCore.QRect(600, 80, 89, 25))
        self.btn_agregar.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_editar = QtWidgets.QPushButton(self.groupBox)
        self.btn_editar.setGeometry(QtCore.QRect(600, 120, 89, 25))
        self.btn_editar.setStyleSheet("background-color: rgb(153, 193, 241);")
        self.btn_editar.setObjectName("btn_editar")
        self.btn_eliminar = QtWidgets.QPushButton(self.groupBox)
        self.btn_eliminar.setGeometry(QtCore.QRect(600, 160, 89, 25))
        self.btn_eliminar.setStyleSheet("background-color: rgb(246, 97, 81);")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.le_buscar = QtWidgets.QLineEdit(self.centralwidget)
        self.le_buscar.setGeometry(QtCore.QRect(30, 300, 361, 25))
        self.le_buscar.setObjectName("le_buscar")
        self.btn_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_buscar.setGeometry(QtCore.QRect(410, 300, 89, 25))
        self.btn_buscar.setObjectName("btn_buscar")
        self.tbv_registrosRegion = QtWidgets.QTableView(self.centralwidget)
        self.tbv_registrosRegion.setGeometry(QtCore.QRect(30, 360, 751, 192))
        self.tbv_registrosRegion.setObjectName("tbv_registrosRegion")
        FrmRegion.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmRegion)
        QtCore.QMetaObject.connectSlotsByName(FrmRegion)
        FrmRegion.setTabOrder(self.btn_limpiar, self.btn_agregar)
        FrmRegion.setTabOrder(self.btn_agregar, self.btn_editar)
        FrmRegion.setTabOrder(self.btn_editar, self.btn_eliminar)
        FrmRegion.setTabOrder(self.btn_eliminar, self.le_identificador)
        FrmRegion.setTabOrder(self.le_identificador, self.le_nombre)
        FrmRegion.setTabOrder(self.le_nombre, self.le_buscar)
        FrmRegion.setTabOrder(self.le_buscar, self.btn_buscar)
        FrmRegion.setTabOrder(self.btn_buscar, self.tbv_registrosRegion)

    def retranslateUi(self, FrmRegion):
        _translate = QtCore.QCoreApplication.translate
        FrmRegion.setWindowTitle(_translate("FrmRegion", "Gestión de región "))
        self.groupBox.setTitle(_translate("FrmRegion", "Datos de la región    "))
        self.lbl_identificador.setText(_translate("FrmRegion", "Identificador"))
        self.lbl_nombre.setText(_translate("FrmRegion", "Nombre"))
        self.btn_limpiar.setText(_translate("FrmRegion", "Limpiar"))
        self.btn_agregar.setText(_translate("FrmRegion", "Agregar"))
        self.btn_editar.setText(_translate("FrmRegion", "Editar"))
        self.btn_eliminar.setText(_translate("FrmRegion", "Eliminar"))
        self.btn_buscar.setText(_translate("FrmRegion", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmRegion = QtWidgets.QMainWindow()
    ui = Ui_FrmRegion()
    ui.setupUi(FrmRegion)
    FrmRegion.show()
    sys.exit(app.exec_())
